server:
  port: 8080
  servlet:
    context-path: /isport-mart-api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sports?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo
    username: root
    password: root
    hikari:
      pool-name: isport-hikari-pool
      maximum-pool-size: 20
      max-lifetime: 1800000
      connection-timeout: 300000
  application:
    name: isport-mart-api